name: 🐛 Bug Report
description: Report a bug or issue with .floppies installation
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug! Please fill out the information below.
  
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: Which operating system are you using?
      options:
        - macOS (Intel)
        - macOS (Apple Silicon M1/M2/M3)
        - Ubuntu
        - Debian
        - Fedora
        - RHEL/CentOS
        - Arch Linux
        - Manjaro
        - Windows (WSL)
        - Windows (Git Bash)
        - Windows (PowerShell)
        - Other (please specify)
    validations:
      required: true
  
  - type: input
    id: os-version
    attributes:
      label: OS Version
      description: What version of the OS are you running?
      placeholder: "e.g., macOS 14.1, Ubuntu 22.04, Windows 11"
    validations:
      required: true
  
  - type: dropdown
    id: installation-type
    attributes:
      label: Installation Type
      description: Which installation option did you choose?
      options:
        - Full Installation
        - Core Essentials Only
        - Custom Installation
        - Update Existing Installation
    validations:
      required: true
  
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true
  
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run './install.sh'
        2. Select option '...'
        3. See error
    validations:
      required: true
  
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what you expected...
    validations:
      required: true
  
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true
  
  - type: textarea
    id: error-output
    attributes:
      label: Error Output
      description: Please paste any error messages or relevant output
      render: shell
      placeholder: Paste error output here...
  
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information...
  
  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have read the documentation (README, FAQ, Platform Setup)
          required: true
        - label: I have included all relevant information above
          required: true
