name: ✨ Feature Request
description: Suggest a new feature or enhancement for .floppies
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide details below.
  
  - type: dropdown
    id: feature-category
    attributes:
      label: Feature Category
      description: What category does this feature fall into?
      options:
        - New Tool/Package
        - New Platform Support
        - Editor/IDE Enhancement
        - Terminal Tool Enhancement
        - Container/Orchestration Tool
        - Cloud Platform Support
        - Security Enhancement
        - Documentation Improvement
        - Performance Improvement
        - Other
    validations:
      required: true
  
  - type: textarea
    id: problem-description
    attributes:
      label: Problem Description
      description: Is your feature request related to a problem? Please describe.
      placeholder: "I'm always frustrated when..."
  
  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: "I would like to see..."
    validations:
      required: true
  
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered
      placeholder: "Alternatively, we could..."
  
  - type: dropdown
    id: platforms
    attributes:
      label: Applicable Platforms
      description: Which platforms should this feature support?
      multiple: true
      options:
        - All Platforms
        - macOS
        - Linux (Ubuntu/Debian)
        - Linux (RHEL/Fedora)
        - Linux (Arch)
        - Windows (WSL)
        - Windows (Native)
  
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
      placeholder: Any additional information...
  
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve my workflow
        - High - Critical for my use case
    validations:
      required: true
  
  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you like to contribute to this feature?
      options:
        - label: I would be willing to implement this feature
        - label: I can help test this feature
        - label: I can help with documentation
